services:
  app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: digitalcoach-mlapi:latest
    stop_signal: SIGINT
    environment:
      - TZ=${timezone}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - type: bind
        source: ${code_source}
        target: /app/backend
    command: gunicorn --bind 0.0.0.0:5000 --pythonpath /app backend.main:application
    ports:
      - "${app_ports}"
    depends_on:
      - redis

  worker:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: digitalcoach-worker:latest
    stop_signal: SIGINT
    environment:
      - TZ=${timezone}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - type: bind
        source: ${code_source}
        target: /app/backend
    command: rq worker --with-scheduler high default low 
    depends_on:
      - redis

  redis:
    hostname: redis
    image: redis:7.0.8-bullseye
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${redis_port}
    volumes:
      - redis_data:/data

volumes:
  redis_data:
